workflows:
  ios-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: apps/client/jeeny
    
    environment:
      flutter: 3.24.0
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      
      - name: Build iOS Simulator
        script: |
          flutter build ios --simulator --debug
      
      - name: Create ZIP
        script: |
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app
    
    artifacts:
      - apps/client/jeeny/build/ios/iphonesimulator/Runner.zip
      - apps/client/jeeny/build/ios/iphonesimulator/Runner.app
