// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf8xQm98WCHYYjIHIhP_7rAiIXYHBZi1k',
    appId: '1:42705554870:web:b0d4bcbd45c1fa921f8517',
    messagingSenderId: '42705554870',
    projectId: 'jeeny-platforme',
    authDomain: 'jeeny-platforme.firebaseapp.com',
    storageBucket: 'jeeny-platforme.firebasestorage.app',
    measurementId: 'G-HL1BZF0TRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVUReqs8n1r0Pl-loS2OMzeUPqx-cXFTg',
    appId: '1:42705554870:android:4846683feb8659ba1f8517',
    messagingSenderId: '42705554870',
    projectId: 'jeeny-platforme',
    storageBucket: 'jeeny-platforme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAicHXPX6fxza551QZN3O-JOdKnIt86sW8',
    appId: '1:42705554870:ios:07863fa58ef34e871f8517',
    messagingSenderId: '42705554870',
    projectId: 'jeeny-platforme',
    storageBucket: 'jeeny-platforme.firebasestorage.app',
    iosBundleId: 'com.jeeny.jeeny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAicHXPX6fxza551QZN3O-JOdKnIt86sW8',
    appId: '1:42705554870:ios:07863fa58ef34e871f8517',
    messagingSenderId: '42705554870',
    projectId: 'jeeny-platforme',
    storageBucket: 'jeeny-platforme.firebasestorage.app',
    iosBundleId: 'com.jeeny.jeeny',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf8xQm98WCHYYjIHIhP_7rAiIXYHBZi1k',
    appId: '1:42705554870:web:fb1d3fded57439581f8517',
    messagingSenderId: '42705554870',
    projectId: 'jeeny-platforme',
    authDomain: 'jeeny-platforme.firebaseapp.com',
    storageBucket: 'jeeny-platforme.firebasestorage.app',
    measurementId: 'G-BTC2M9EG3M',
  );
}